### ISSUE TITLE
Laptop TurnOffWrapper doen't work if executed serverside

### ISSUE THREAD

**Issue by y0014984** [y0014984/Advanced-Equipment#102]
I was testing the shutdown on power exceed in a separate branch with new power settings. I used a dedicated server.

- 1 generator (5.000 W or 5/3600 power outlet)
- 1 laptop
- 17 portable lamps double (300 W or 0.3/3600 power consumption)

I started the generator, then I connected and started all devices. With turning on the last lamp, every device should power down. Generator and all lamps powered down, but not the laptop. 

I think I figured out, that the problem is the call of the TurnOffWrapper in fnc_updatePower.sqf, line 23

The TurnOffWrapper doesn't work if executed serverside, but I don't know why. The turnOff function for the laptop uses progress-bar-shit, but this isn't called due to the "_silent" flag, set in this function call.

In singleplayer this also doesn't work. This also doesn't make any sense, because I can execute the wrapper in the debug console.

@GermanHydrogen : Any ideas?

**Comment by GermanHydrogen** [comment]
**Could not reproduce.**
The laptop should only turn off, if the battery is empty, which I prosume is not the case.
Test results:
The generator and lamps turn off like they should, and the laptop battery is not charged any longer.
