### ISSUE TITLE
Armaos html special characters

### ISSUE THREAD

**Issue by GermanHydrogen** [y0014984/Advanced-Equipment#154]
Special characters like `<`, `>` and `&` interfere with the parseText at the end of the terminal pipeline.
These are currently disabled.
A solution would be, to always keep track of the user input in the inputBuffer, which is kept as a string and
change the terminalBuffer to structured text.
This allows the usage of the `text` command to convert strings to structured text which is compatible
with these special characters.

**Comment by y0014984** [comment]
solved via #217
