### ISSUE TITLE
Corrupt permissions on files created via addFile Module

### ISSUE THREAD

**Issue by y0014984** [y0014984/Advanced-Equipment#158]
Files creates in the 3DEN Editor via the addFile Module lack of correct permissions. 

Steps to reproduce:
Create User "exampleuser"
AddFile "/home/exampleuser/test.txt"
Set Permissions to allow "exampleuser" everything
Load mission and login with "exampleuser"

Result:
"ls -al" returns script error. Directory is owned by "root" instead of "exampleuser"

Annotation: If you do the same for root user, for example "home/root/test.txt", the folder is complety missing the permissions if you do "ls -al"

**Comment by y0014984** [comment]
Perhaps the problem is only related to the intermediate folders or the coincidence that the folders are user folders. Needs to be verified.

**Comment by GermanHydrogen** [comment]
Comment on the annotation:
The home directory of root is `/root/` and not `/home/root/`
