### ISSUE TITLE
Add Option to change the name of Terminal from Yoo Industries.

### ISSUE THREAD

**Issue by L3gion-cmd** [y0014984/Advanced-Equipment#409]
![ArmaOs](https://github.com/y0014984/Advanced-Equipment/assets/40768093/9fc5f965-149b-4ca2-acf9-879353031060)

**Feature Request.**

It would be nice if we can change the name from Yoo Industries to something else.

It would be nice if we could do that per computer / Object so we can have "More companies" have their own terminal system.

If its not possible to do per object computer name. Either too complicated to implement or to tedious.
It would be at least nice to have names Per Side. For Example
Blufor have: Bluefor Industries 
Opfore have: Opfor Industries 
ect..
And ofc add a option so player can change the side computer name..

This gives a little "Roleplay" in to the game.

**Comment by y0014984** [comment]
@L3gion-cmd This feature is part of pull request #412 and is currently in review. It will be part of the next AE3 release. Can't say when this will happen. You can change the brand name for every computer individually via a simple line of code inside the init-field of the laptop, see pull request.

**Comment by y0014984** [comment]
PR is approved and will be part of next release. I close this Issue for now. If you want to check it out, feel free to use the dev branch.
