### ISSUE TITLE
ArmaOS: Undefined battery level on standby

### ISSUE THREAD

**Issue by GermanHydrogen** [y0014984/Advanced-Equipment#77]
Setting the power mode of a laptop to standby produces errors regarding the battery level to be undefined.
Checking the battery level after, also produces the same error.

**Comment by GermanHydrogen** [comment]
Same error on connecting a laptop to a generator.

**Comment by y0014984** [comment]
@GermanHydrogen Unfortunately, the project is quite dead right now. But I would think about a revive if someone would join the project or at least contributes a significant amount of pull requests. If you are interested, please PM me.
