### ISSUE TITLE
ArmaOS Function Rework

### ISSUE THREAD

**Issue by GermanHydrogen** [y0014984/Advanced-Equipment#85]
The current system is not very flexible and adding a new function requieres editing unrelated code in many places.

Changes:

- [x] Abstracting functions to executable files with global links
- [x] Defining global links in seperate config

**Comment by y0014984** [comment]
I'm not sure what this ticket is about. Was this part of your already done rework or is this something new, like custom functions that can be executed in ArmaOS directly and having a filesystem representation?

**Comment by GermanHydrogen** [comment]
There is no real flexible function system implace. At the momentent all ArmaOS functions are hardcoded.
