### ISSUE TITLE
ArmaOS Shell doesn't scroll correctly

### ISSUE THREAD

**Issue by GermanHydrogen** [y0014984/Advanced-Equipment#88]
The shell doesn't scrolls correctly, when a function has a long multiline output.

![grafik](https://user-images.githubusercontent.com/41219647/148686822-959a03b8-70ec-48bc-ac44-5d997aca43ba.png)

**Comment by y0014984** [comment]
This ist fixed in PR https://github.com/y0014984/Advanced-Equipment/pull/90
